# Generated by Django 6.1.1 on 2026-10-05 22:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bebidas',
            fields=[
                ('ID_Bebidas', models.AutoField(primary_key=True, serialize=False)),
                ('bebidas', models.CharField(choices=[('EXPRESSO', 'Expresso'), ('CAPPUCCINO', 'Cappuccino'), ('CHOC_QUENTE', 'Chocolate quente cremoso'), ('BEBIDAS_GELADAS', 'Bebidas geladas'), ('OUTRO', 'Outro')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Canal',
            fields=[
                ('ID_Canal', models.AutoField(primary_key=True, serialize=False)),
                ('descoberta', models.CharField(choices=[('INDCAC', 'Indicação'), ('INSTAG', 'Instagram'), ('GOOGLE', 'Google'), ('CASMTS', 'Casamentos.com'), ('OUTROS', 'Outro')], max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('ID_Categoria', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(choices=[('SOCIAL', 'Social'), ('CORPORATIVO', 'Corporativo')], max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('Email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('telefone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')])),
                ('nome', models.CharField(max_length=80)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Duracao',
            fields=[
                ('ID_Duracao', models.AutoField(primary_key=True, serialize=False)),
                ('duracao', models.CharField(choices=[('DIA', 'Um dia'), ('DIAS', 'Mais de um dia')], default='DIA', max_length=5)),
                ('data_inicio', models.DateField()),
                ('data_termino', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_termino', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Servico_Adicional',
            fields=[
                ('ID_Servico', models.AutoField(primary_key=True, serialize=False)),
                ('drip_station', models.BooleanField(default=False)),
                ('impressora', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('ID_Evento', models.AutoField(primary_key=True, serialize=False)),
                ('endereco', models.CharField(max_length=255)),
                ('num_convidados', models.IntegerField()),
                ('mensagem', models.TextField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, max_length=500, null=True)),
                ('FK_Canal', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='ristretto.canal', verbose_name='Canal de descoberta deste Evento')),
                ('FK_Categoria', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='ristretto.categoria', verbose_name='Categoria do evento')),
                ('FK_Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ristretto.cliente', verbose_name='Cliente Responsável')),
                ('FK_Duracao', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='ristretto.duracao', verbose_name='Duração do Evento')),
                ('FK_Servico', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='ristretto.servico_adicional', verbose_name='Serviço Adicional do Evento')),
            ],
        ),
        migrations.CreateModel(
            name='Corporativo',
            fields=[
                ('ID_Corporativo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_evento', models.CharField(choices=[('REUNIAO', 'Reunião/Treinamento'), ('FEIRA', 'Feira/Congresso'), ('LANCAMENTO', 'Lançamento de produto'), ('FIM_ANO', 'Evento de fim de ano'), ('OUTRO', 'Outro')], max_length=15)),
                ('outro_evento', models.CharField(blank=True, max_length=50, null=True)),
                ('estimativa_doses', models.IntegerField(choices=[(200, '200 doses'), (300, '300 doses'), (400, '400 doses'), (500, '500 doses'), (600, '600 doses'), (700, '700 doses'), (800, '800 doses'), (900, '900 doses'), (1000, '1000 doses')], verbose_name='Estimativa de Doses diárias')),
                ('mais_doses', models.CharField(blank=True, max_length=30, null=True)),
                ('copos_personalizados', models.BooleanField(default=False)),
                ('detalhes', models.TextField(blank=True, max_length=255, null=True)),
                ('FK_Bebidas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ristretto.bebidas')),
                ('FK_Evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ristretto.evento', verbose_name='Evento Corporativo Relacionado')),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('ID_Social', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_evento', models.CharField(choices=[('CASAMENTO', 'Casamento'), ('ANIVERSARIO', 'Aniversário'), ('FORMATURA', 'Formatura'), ('CONFRATERNIZACAO', 'Confraternização Particular'), ('OUTRO', 'Outro')], max_length=30)),
                ('outro_evento', models.CharField(blank=True, max_length=20, null=True)),
                ('bebida_alcoolica', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('TALVEZ', 'Talvez')], max_length=6)),
                ('FK_Evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ristretto.evento', verbose_name='Evento Social Relacionado')),
            ],
        ),
    ]
