# Generated by Django 6.1.1 on 2026-10-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ristretto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canal',
            name='descoberta',
            field=models.CharField(choices=[('INDCACAO', 'Indicação'), ('INSTAGRAM', 'Instagram'), ('GOOGLE', 'Google'), ('CASAMENTOS.COM', 'Casamentos.com'), ('OUTROS', 'Outro')], max_length=15),
        ),
    ]
