# Generated by Django 6.1.1 on 2026-10-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ristretto', '0002_alter_canal_descoberta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corporativo',
            name='FK_Bebidas',
        ),
        migrations.AddField(
            model_name='corporativo',
            name='FK_Bebidas',
            field=models.ManyToManyField(blank=True, to='ristretto.bebidas', verbose_name='Bebidas Selecionadas'),
        ),
    ]
