# Generated by Django 6.1.1 on 2026-10-08 00:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ristretto', '0003_remove_corporativo_fk_bebidas_corporativo_fk_bebidas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canal',
            name='descoberta',
            field=models.CharField(choices=[('INDICACAO', 'Indicação'), ('INSTAGRAM', 'Instagram'), ('GOOGLE', 'Google'), ('CASAMENTOS.COM', 'Casamentos.com'), ('OUTROS', 'Outro')], max_length=15),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{10,11}$')]),
        ),
    ]
